* Как отсканировать данные из задания на компьютер.
** TLDR

#+BEGIN_SRC shell 
tesseract -l rus photo.jpg out
#+END_SRC

После этого в файле out.txt будет текст задания.

** Важное замечание про установку tesseract

Мне не составило труда его установить, потому что пользуюсь
операционной системой в которой есть пакетный менеджер
для установки бинарных пакетов собранных из исходников в портах.

Однако важно заметить, что кроме самого tesseract нужно установить
пакеты, которые обеспечивают в нём поддержку сканирования отдельных
письменностей. В windows просто оставить галочку на пункте
Language Data в установщие.

#+BEGIN_SRC
  tesseract-equ-4.1.0v0 # Для математических выражений
  tesseract-rus-4.1.0v0 # Для русского языка
#+END_SRC

Установить на windows:
https://github.com/UB-Mannheim/tesseract/wiki#tesseract-installer-for-windows


** Альтернатива

Tesseract OCR (optical character recognition) это не единственная программа,
которая может быть использована для считывания текста с картинки.
Помню, что ABBYY делали программу с аналогичной функциональностью в виде плагина для word.

** Могу помочь

Я думал, что сканирование займет пол минуты, а заняло секунд пять.
Если у кого-то не получиться установить и заставить работать tesseract, то можете мне
скинуть файл с картинкой, предварительно его переименовав в stats_N.jpg где N номер
вашего варианта, например 13 или 05 ( с ведущим нулём, если номер меньше десяти).
После чего сложив все файлы в один каталог я просто запущу скрипт, который запустит
tesseract для каждого файла. Только давайте до восьмого апреля.
